//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long Taskid { get; set; }
        public int UserId { get; set; }
        public string TaskName { get; set; }
        public System.DateTime TaskDate { get; set; }
        public short NumberOfHours { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public string Comments { get; set; }
    
        public virtual User User { get; set; }
    }
}
